[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "template-code"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Thibaud ROBIN", email = "trobin@esgi.com" }
]
requires-python = ">=3.11"




dependencies = [
    'requests',
    'scapy',
    'pygal',
    'fpdf2',
    'pytest',
    'capstone',
    'python-dotenv',
    "reportlab>=4.5.1",
    "svglib>=1.6.0",
]


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["tp1*", "tp2*", "tp3*"]
